### ISSUE TITLE
Crash windows 10

### ISSUE THREAD

**Issue by thijsdamen** [pajlada/TempestNotifier#2] opened 2015-08-05 18:14 UTC
Instant crash on windows 10. (tell me how and I'll supply logs)

Tried both running as admin and non-admin.

**Comment by pajlada** [comment] 2015-08-05 18:16
This is using version 0.5.0-alpha right?

**Comment by pajlada** [comment] 2015-08-05 19:35
I've updated the 0.5.0-alpha to Release 5, if you could try that: https://github.com/pajlada/TempestNotifier/releases/tag/v0.5.0-alpha

As a heads up, any screenshots you take with Path of Exile while the program is running are automatically uploaded to my server.

**Comment by thijsdamen** [comment] 2015-08-07 16:27
The alpha version works. It was the 0.4.2 version that was crashing

**Comment by pajlada** [comment] 2015-08-07 16:27
Ah neat, awesome! Thanks for letting me know

**Comment by therealbungus** [comment] 2015-08-09 18:48
Downloaded the latest version, v0.5.0-alpha release 5 and it is crashing on startup too. Im on windows 10. The 0.4.2 version works without issue, any idea what the issue is?

**Comment by pajlada** [comment] 2015-08-09 18:51
I'll try to include debug symbols for the next release, or some sort of log files.
For now, you can make sure you have the .NET framework installed on your PC. (see http://www.microsoft.com/net )

**Comment by therealbungus** [comment] 2015-08-11 05:05
I am on windows 10, the .NET frameworks are already installed. There are no download links for Win10 and the ones you can download give an error when trying to install. Any other possible solutions?

**Comment by pajlada** [comment] 2015-08-25 11:59
@trecko1234 If you're still curious about the project, please give 0.6.0 a try https://github.com/pajlada/TempestNotifier/releases/tag/v0.6.0
Let me know how it goes, thanks!

**Comment by therealbungus** [comment] 2015-08-25 17:47
Well I went back to windows 7, and im still getting crashes on startup. Sent an error report, hopefully that should say something on why it's not working?

**Comment by pajlada** [comment] 2015-08-25 17:55
@trecko1234 It seems the crash occured if you had never taken a screenshot with Path of Exile's screenshot hotkey before, silly oversight by me. Fixed in 0.6.1 https://github.com/pajlada/TempestNotifier/releases/tag/v0.6.1

**Comment by therealbungus** [comment] 2015-08-25 17:57
Doesnt crash on startup anymore, thanks. Ill let you know if any other problems occur.

**Comment by pajlada** [comment] 2015-08-25 18:18
Closing this issue for now then. If it crashes again we can start a new issue :smile:

**Closed as completed by pajlada** 2015-08-25 18:18 UTC
